### ISSUE TITLE
django.db.utils.OperationalError: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by zN3utr4l** [avryhof/huey_django_orm#3]
I found another problem, I described it here: https://github.com/coleifer/huey/issues/764.

Does huey or huey_django_orm have this problem?

**Comment by VBobCat** [comment]
@zN3utr4l , please check and report if the problem persists after upgrading to huey-django-orm==23.12.10.0

**Comment by zN3utr4l** [comment]
Fixed
