### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by akprasad** [avryhof/huey_django_orm#6]
Thanks for this library! I'm excited to use it to support our Django + Huey integration.

I'd like to request that you create a new PyPI release to incorporate your change [here](https://github.com/avryhof/huey_django_orm/commit/617588d23cc32743e6ca12d8f18a1f3dcb408176). Otherwise, I find that using this library on `23.12.10.0` requires running `makemigrations`, and the new migration file is created in our virtualenv instead of our main code.

Edit: here's the migration file that is generated for us when using `23.12.10.0`:

```
# Generated by Django 5.0.2 on 2024-04-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huey_django_orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hueyschedule',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='hueytask',
            options={'ordering': ('-priority', 'id')},
        ),
    ]
```

**Comment by avryhof** [comment]
Done.  Enjoy!
